
eureka.client.service-url.defaultZone=http://k8s-coveeurekaingress-099090752f-315466093.ap-south-1.elb.amazonaws.com/eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}
eureka.instance.hostname=cove-user-backend-host
eureka.instance.preferIpAddress=true 

#prometheus integration

# Enable Actuator endpoints
#management.endpoints.web.exposure.include=prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.health.db.enabled=true
management.info.env.enabled =true
info.app.name=cove-user-service
info.app.description=cove-user-service
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=POST,GET,PUT,OPTIONS,DELETE
management.endpoints.web.cors.allowed-headers=*


#spring.main.allow-bean-definition-overriding=true




#tomcat
spring.main.web-application-type=reactive
server.tomcat.basedir=access_log
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms) "%{x-rtls-traceid}i"
#server.tomcat.accesslog.max-days=14
jwt.secret=qYOZNk7GTA6uR9xoB1GjPFcsh1FBeFu2qYOZNk7GTA6uR9xoB1GjPFcsh1FBeFu2
jwt.secret.refresh.token=644bfdb6e14b0f3361928445e8ae8f25df98a88bb4cf64dea4296e7dcc47a9e37561251d890d8e063ad3bd886377f2b38c6d9adbedf681aa00da68edd7f0e94eddcb88c5df9b816c04b021de3a778434ccedd20f386dfd74ed2be5ae18b3f3bcd630151e8c8d6a5f93a18bb1650b75d5c2044586df349108adf1035bbdbddf6b2f0280b97f832905c8d2f1eeff3cad53f1ac6df0e8e5d3478dea9d0cf84c6840f491adf43f585266a7e71f5280b6da4ec8dba52eaf1d046d6dd51c340c18905b5006d273ff4575debb9efcaf80106ea7af93fd3fd968b35ab56dfe47f7cba8976a9f4a4fcba18248bccf5411bf814a7cbac6ec4a12e4817c8cc23ded184c34a1
jwt.token.validity=1800000
jwt.refresh.token.validity=86400000
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true



testing.text=Cove User Service



spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=covecollaberadigital@gmail.com
spring.mail.password=abmedqpfrirzecrl
spring.mail.transport.protocol=smtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://cove-db.chioww02cxoo.ap-south-1.rds.amazonaws.com:3306/cove?useSSL=false&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=coveadmin2024
spring.datasource.initialization-mode=always

spring.jpa.generate-ddl=true
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.mvc.dispatch-options-request=true


#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



